### ISSUE TITLE
Local crashes upon terminating while downloading and restarting.

### ISSUE THREAD

**Issue by csinko** [stohio/software-lab#42]
To reproduce:

1. Delete the local/software folder
1. Start remote
3. Start local
4. Terminate local (ctrl c) while software is downloading
5. restart local.

Here is the console printout of the error:
```
2017/05/29 11:19:58 Starting Local Server -> 127.0.0.1:8080
2017/05/29 11:19:58 Local IP: 192.168.1.34
2017/05/29 11:19:58 Hostname: soam-z87
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x67f279]

goroutine 1 [running]:
main.DownloadFromLocal(0xc4200fc540, 0xc42010c8c0, 0xc4201007b0, 0x10, 0x0, 0x0)
	/home/csinko/Projects/go/src/github.com/stohio/software-lab/local/main.go:320 +0x3b9
main.CheckOrDownload(0xc4200fa740, 0x2, 0x4, 0xc420108500)
	/home/csinko/Projects/go/src/github.com/stohio/software-lab/local/main.go:253 +0x46b
main.DownloadSoftware(0xc42012a000)
	/home/csinko/Projects/go/src/github.com/stohio/software-lab/local/main.go:228 +0x8e
main.main()
	/home/csinko/Projects/go/src/github.com/stohio/software-lab/local/main.go:123 +0x750
```

**Comment by mattroseman** [comment]
This is caused by nodes checking to see if there is a network before deciding whether to download from local or remote. However if there is a network with no enabled nodes, then there is nothing to download from, and the program crashes.
